### ISSUE TITLE
Option to combine multiple coverage files

### ISSUE THREAD

**Issue by anilbey** [plasma-umass/slipcover#12]
Hi,

The tool works fine for a single run but it does not have the functionality to combine multiple coverage files.

Could you either add the functionality to combine multiple coverage data files or provide a compatible output that can used by coverage.py's `combine` command [1]?

Thanks in advance!

1. https://coverage.readthedocs.io/en/6.3.2/api_coverage.html?highlight=combine#coverage.Coverage.combine

**Comment by jaltmayerpizzorno** [comment]
Sounds good, thank you!

**Comment by jaltmayerpizzorno** [comment]
Implemented in v1.0.5.
