### ISSUE TITLE
pypy support?

### ISSUE THREAD

**Issue by cfbolz** [plasma-umass/slipcover#13]
hi @jaltmayerpizzorno!

Great project, this is a fun approach! I was wondering whether you would be interested in adding PyPy support? I briefly looked, and there seems not a lot missing: The C extension seems to just work, the only problem is some detail around the way PyPy does builtin functions. If there is interest, I would be happy to open up a pull request to deal with the latter! (if not, feel free to just close the issue)

**Comment by jaltmayerpizzorno** [comment]
Hi @cfbolz, thank you!  I haven't explored adding pypy support yet.  Assuming it doesn't get in the way of research too much, it would be great to have!

**Comment by cfbolz** [comment]
fair enough! I've opened the above PR, the only fundamental change, which makes slipcover work. will open another one to add it to CI (only pypy3.8 supported by the setup-python action though).

performance isn't as good as CPython for a bunch of reasons (pypy is much faster in the first place, C extensions are worse on pypy). I briefly tried with a pure Python tracker, which helped and could probably improved with more careful thinking about the locking needed.

**Comment by jaltmayerpizzorno** [comment]
Hi, sorry for the delay... have been hard at work adding CPython 3.11 support.  I've merged your PR now.

Slipcover's locking does need some rework.

I'd love to see the benchmarks with pypy if you cared to run them... they're in `benchmarks/run_benchmarks.py`.
