### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by markshannon** [plasma-umass/slipcover#15]
Do you plan to support Python 3.11?

**Comment by emeryberger** [comment]
Yes, a release that supports Python 3.11 is imminent!

**Comment by jaltmayerpizzorno** [comment]
I've now merged the code to support 3.11 into `main`.  Some things could be nicer, but it seems to work fine.
I'm working on a packaging issue and should be making a release soon.

**Comment by jaltmayerpizzorno** [comment]
v0.1.7 with Python 3.11 support is now out.

**Comment by jaltmayerpizzorno** [comment]
Hi @markshannon, do you know of a Python roadmap at this level?  Adapting our instrumentation for 3.11 was a fair amount of work, and if available I would love to get a heads up :)

Also... if there was ever any interest in adding an instrumentation API for Python, I'd be happy to contribute whatever I can. It could take pressure off tracing for uses like coverage, fuzzing, etc., which (as our work here is showing) may not be the ideal interface.

**Comment by markshannon** [comment]
Like [PEP 669](https://peps.python.org/pep-0669/)?

**Comment by jaltmayerpizzorno** [comment]
Indeed :)  I didn't see much about it on `python-dev`.  Is there a different mailing list?

**Comment by markshannon** [comment]
https://discuss.python.org/t/pep-669-low-impact-monitoring-for-cpython/13018
