### ISSUE TITLE
please support gunicorn start django code coverage measure

### ISSUE THREAD

**Issue by jokerbo1** [plasma-umass/slipcover#18]
please support gunicorn start django code coverage measure,thank you

**Comment by emeryberger** [comment]
Please provide a sample program and instructions on running it so we can see what the issue is.

**Comment by jokerbo1** [comment]
hello, running  command 
> /home/blibee/miniconda3/envs/robotsocketenv/bin/gunicorn -b 0.0.0.0:8011 gaia.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --max-requests 1500 --max-requests-jitter 2000

i see slipcover application support command format is
> python3 -m slipcover -m pytest
this command not support my current application startup .i expected mulproc runing  is collect service code coverage .

This is my running scene, thank you~

**Comment by emeryberger** [comment]
What we need are installation instructions / code. In particular, here, we'd need code for the gaia application.

**Comment by jaltmayerpizzorno** [comment]
Closing for lack of information
