### ISSUE TITLE
`--fail-under` flag as in `coverage`

### ISSUE THREAD

**Issue by rec** [plasma-umass/slipcover#24]
Good day, and thank you for this very interesting project!

I'm going to file a few issues regarding feature parity with `coverage`, but feel free to do with them as you wish including nothing.  :-)

Or, if you are open to pull requests, I could probably knock at least a few of them out.

----

The one big reason that I cannot yet adopt slipcover in my current project is that it is missing `--fail-under` or some facility like that which fails when the test coverage drops below a certain level.

I might well have missed this feature in your program of course.

Here's the documentation: https://coverage.readthedocs.io/en/6.4.4/cmd.html#reporting

Doesn't seem horrifyingly hard...

**Comment by jaltmayerpizzorno** [comment]
Yea, this sounds trivial to implement.  I'd be happy to add this in the next release, but sure, we're open to PR.

**Comment by rec** [comment]
Ah, sorry, I simply ran out of time to do this. :-/

Hoping this all goes well for you!
