### ISSUE TITLE
Codecov compat?

### ISSUE THREAD

**Issue by jab** [plasma-umass/slipcover#30]
I checked the docs, tracker, and https://docs.codecov.com/docs/supported-report-formats docs, and still couldn’t tell if any of the supported output formats (is it currently just json?) are compatible with codecov.io, so thought I’d try asking here. Thanks!

**Comment by jaltmayerpizzorno** [comment]
That link doesn't work for me, but I searched for the supported formats, and it doesn't look like they support ours.
Yes, currently Slipcover only outputs text (intended for human use) and JSON (everything else).
Our JSON format is intended to be just about identical to [coverage.py](https://github.com/nedbat/coveragepy)'s...
It's not clear to me that *that* is supported, either, though.

I wonder if one of the formats they support is relatively close to ours...

**Comment by guillaumeLepape** [comment]
Hi. I tried few days ago to upload json coverage to codecov. I got the following the error: "the report is not usuable". After a deeper look into the codecov code, I found the error. Codecov is infering the coverage type from few elements in the file. For json coverage file, the code is the following : https://github.com/codecov/worker/blob/861583604119da9c607b588055e4f175a784a103/services/report/languages/pycoverage.py#L22

This `show_contexts` flag was the missing element, by adding it in the coverage file, codecov is able to recognize my report and display the coverage correctly. The measure context feature coverage py is a not supported slipcover feature. I'm not using this feature (I didn't know about it actually).
My proposal, for now, would be to hardcode this flag to False to be able to upload report to codecov.

**Comment by guillaumeLepape** [comment]
I raised this pr to fix the issue, can you please review? https://github.com/plasma-umass/slipcover/pull/49

**Comment by jab** [comment]
Since #49 was merged and released, is this issue fixed and can it be closed? If so, worth mentioning in the release notes? (codecov.com compatibility is not currently mentioned anywhere on https://github.com/plasma-umass/slipcover/releases which it looks like is where notable changes are listed.)

**Comment by jaltmayerpizzorno** [comment]
> Since #49 was merged and released, is this issue fixed and can it be closed? If so, worth mentioning in the release notes? (codecov.com compatibility is not currently mentioned anywhere on https://github.com/plasma-umass/slipcover/releases which it looks like is where notable changes are listed.)

Yes, indeed! Done.
