### ISSUE TITLE
slipcover causes eager binding of celery tasks

### ISSUE THREAD

**Issue by crockeo** [plasma-umass/slipcover#55]
I was integrating slipcover with a project and found that it caused several tests in our test suite to fail. After some debugging, it turns out that it was caused by `slipcover` making Celery [`Task`s](https://docs.celeryq.dev/en/main/reference/celery.app.task.html#celery.app.task.Task) to be eagerly bound to their [`Celery` app](https://docs.celeryq.dev/en/main/reference/celery.html#celery.Celery). Specifically:

- Inside of `is_patchable_function` y'all use `inspect.isfunction`.
- `inspect.isfunction` uses `isinstance(<thing>, FunctionType)`.
- `isinstance` causes a `Task` to bind to its app.

<details>
<summary>Example stack trace</summary>

```
  File "/usr/local/lib/python3.10/site-packages/slipcover/slipcover.py", line 519, in is_patchable_function
    return inspect.isfunction(func) and type(func.__code__) is types.CodeType
  File "/usr/local/lib/python3.10/inspect.py", line 288, in isfunction
    return isinstance(object, types.FunctionType)
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 94, in __class__
    return self._get_class()
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 90, in _get_class
    return self._get_current_object().__class__
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 294, in _get_current_object
    return self.__evaluate__()
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 324, in __evaluate__
    thing = Proxy._get_current_object(self)
  File "/usr/local/lib/python3.10/site-packages/celery/local.py", line 105, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 489, in _task_from_fun
    task.bind(self)  # connects task to this app
```

</details>

This can cause unexpected changes in a celery `Task`'s behavior because the `Task` inherits certain configurations from the `Celery` app at `bind`-time. Typically it's bound the first time it's executed, but this causes it to be bound at import-time instead.

I think this may be more Celery's fault than slipcover, but I thought you all may want to know about a potential behavior change when using slipcover.

(And: hello from a UMass CS alum. Super cool to see PLASMA continuing to make awesome stuff.)

**Comment by huguesb** [comment]
@crockeo fwiw, I ran into a similar issue once when I was hooking into the Python import machinery, and switching from `isinstance(x, types.ModuleType)` to `type(x) is types.ModuleType` solved the problem for me.  You might try changing `is_patchable_function` in a similar way and see if it solves your problem

**Comment by jaltmayerpizzorno** [comment]
Thank you for creating the issue!

Yes, it can be tricky to introspect without triggering side effects, especially when other packages "cleverly" make use of dynamic behavior.

The issue here is that `Celery` overrides `__class__`, which `isinstance()` may call. We may be ok here just checking for the presence of `__code__` (and its type). I'll poke around a bit.

(and: hello there!)

**Comment by jaltmayerpizzorno** [comment]
It seems like we can side step the `__class__` issue by using `issubclass(type(x), theType)` instead of `isinstance(x, theType)`.

**Comment by jaltmayerpizzorno** [comment]
I added this to SlipCover... please test when you can (right now, only off GitHub; release to come later) and re-open if still not working.
